-- Migration 0004: listings and everything that hangs off a listing.
--
-- DESIGN NOTES
-- * listings.id is a UUID generated by the application (hard to guess in /dashboard/listings/:id/edit).
-- * DRAFTS: the listing wizard saves progress step by step, so most columns are nullable.
--   The CHECK below guarantees that anything beyond draft/deleted is complete.
-- * Soft delete: status = 'deleted' (rows are never removed by normal user actions).
-- * Money is stored as whole BDT (taka) integers. "Estimated monthly cost" is NOT stored;
--   it is derived from the recurring cost columns in application code.
-- * owner_id uses ON DELETE RESTRICT: a user who still owns listings cannot be hard-deleted by accident.

CREATE TABLE listings (
  id                 TEXT PRIMARY KEY,
  owner_id           TEXT NOT NULL REFERENCES "user" ("id") ON DELETE RESTRICT,
  title              TEXT,
  slug               TEXT NOT NULL UNIQUE,
  description        TEXT,
  property_type      TEXT NOT NULL
    CHECK (property_type IN ('mess', 'mess_seat', 'room', 'house', 'flat', 'sublet')),
  status             TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'pending', 'published', 'paused', 'rejected', 'deleted')),
  availability_status TEXT NOT NULL DEFAULT 'available'
    CHECK (availability_status IN ('available', 'available_from', 'unavailable', 'rented', 'occupied')),
  city_id            INTEGER REFERENCES cities (id) ON DELETE RESTRICT,
  area_id            INTEGER REFERENCES areas (id) ON DELETE RESTRICT,
  address            TEXT,
  latitude           REAL CHECK (latitude  BETWEEN -90  AND 90),
  longitude          REAL CHECK (longitude BETWEEN -180 AND 180),
  rent_amount        INTEGER CHECK (rent_amount >= 0),
  advance_amount     INTEGER CHECK (advance_amount >= 0),
  meal_cost          INTEGER CHECK (meal_cost >= 0),
  electricity_cost   INTEGER CHECK (electricity_cost >= 0),
  wifi_cost          INTEGER CHECK (wifi_cost >= 0),
  other_monthly_cost INTEGER CHECK (other_monthly_cost >= 0),
  available_from     TEXT,
  created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  published_at       TEXT,
  CHECK (
    status IN ('draft', 'deleted')
    OR (
      title IS NOT NULL AND city_id IS NOT NULL AND area_id IS NOT NULL
      AND latitude IS NOT NULL AND longitude IS NOT NULL AND rent_amount IS NOT NULL
    )
  )
);

-- Index plan (matches the blueprint's "likely indexes"; composites are driven by real query patterns):
--   slug             -> UNIQUE constraint above (listing detail page)
--   owner_id         -> prefix of idx_listings_owner_status (owner dashboard)
--   status, type     -> prefixes/columns of the two composite indexes below
CREATE INDEX idx_listings_owner_status  ON listings (owner_id, status);
CREATE INDEX idx_listings_city_id       ON listings (city_id);
CREATE INDEX idx_listings_area_id       ON listings (area_id);
CREATE INDEX idx_listings_public_search ON listings (status, city_id, property_type, rent_amount);
CREATE INDEX idx_listings_geo           ON listings (status, latitude, longitude);
CREATE INDEX idx_listings_availability  ON listings (availability_status);
CREATE INDEX idx_listings_published_at  ON listings (published_at);
CREATE INDEX idx_listings_created_at    ON listings (created_at);
CREATE INDEX idx_listings_updated_at    ON listings (updated_at);

-- Image metadata only. The image bytes live in R2; object_key points to them.
CREATE TABLE listing_images (
  id         TEXT PRIMARY KEY,
  listing_id TEXT NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
  object_key TEXT NOT NULL UNIQUE,
  alt_text   TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_listing_images_listing ON listing_images (listing_id, sort_order);

CREATE TABLE listing_facilities (
  listing_id  TEXT    NOT NULL REFERENCES listings (id)   ON DELETE CASCADE,
  facility_id INTEGER NOT NULL REFERENCES facilities (id) ON DELETE CASCADE,
  PRIMARY KEY (listing_id, facility_id)
) WITHOUT ROWID;
CREATE INDEX idx_listing_facilities_facility ON listing_facilities (facility_id);

CREATE TABLE listing_audiences (
  listing_id TEXT NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
  audience   TEXT NOT NULL CHECK (audience IN ('student', 'bachelor', 'family', 'male', 'female')),
  PRIMARY KEY (listing_id, audience)
) WITHOUT ROWID;
