import { createRequestHandler, RouterContextProvider } from "react-router";
import { cloudflareContext } from "../app/server/context.server";
import type { AppEnv } from "../app/server/env.server";
import { withSecurityHeaders } from "../app/server/security-headers.server";

// `virtual:react-router/server-build` is generated by React Router at build time.
// @ts-ignore -- virtual module without a guaranteed type declaration; its shape is validated by createRequestHandler.
const requestHandler = createRequestHandler(() => import("virtual:react-router/server-build"), import.meta.env.MODE);

export default {
  async fetch(request, env, ctx) {
    // Bindings are only reachable on the server: they are placed in the router context here
    // and read in loaders/actions/middleware through `context.get(cloudflareContext)`.
    const context = new RouterContextProvider();
    context.set(cloudflareContext, { env, ctx });
    const response = await requestHandler(request, context);
    return withSecurityHeaders(response);
  },
} satisfies ExportedHandler<AppEnv>;
